package mapping;
// Generated Sep 25, 2018 11:27:24 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;




/**
 * Questiontable generated by hbm2java
 */

@Entity
public class Questiontable  implements java.io.Serializable {

     @Id
     @GeneratedValue
     private short id;
     private String question;
     private String option1;
     private String option2;
     private String option3;
     private String option4;
     private String answer;

    public Questiontable() {
    }

    public Questiontable(short id, String question, String option1, String option2, String option3, String option4, String answer) {
       this.id = id;
       this.question = question;
       this.option1 = option1;
       this.option2 = option2;
       this.option3 = option3;
       this.option4 = option4;
       this.answer = answer;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getOption1() {
        return this.option1;
    }
    
    public void setOption1(String option1) {
        this.option1 = option1;
    }
    public String getOption2() {
        return this.option2;
    }
    
    public void setOption2(String option2) {
        this.option2 = option2;
    }
    public String getOption3() {
        return this.option3;
    }
    
    public void setOption3(String option3) {
        this.option3 = option3;
    }
    public String getOption4() {
        return this.option4;
    }
    
    public void setOption4(String option4) {
        this.option4 = option4;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


